article/urls.py
from django.contrib import admin
from django.urls import path
from . import views                                     #import views.py du repertoire actuel

app_name="article"

urlpatterns = [
    path('create/',views.index,name="index"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addarticle/', views.addArticles, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.updateArticle, name="update"),
    path('delete/<int:id>', views.deleteArticle, name="delete"),
    path('articles/', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment"),
]

#a partir de navbar :  href="/article/dashboard/  , path /article/ envois vers article/url.py selon blog/urls.py
#dans url.py   path  dashboard/  views.dashboard  envois vers fichier  article/views.py fonction dashboard()
#avec attribue  dashboard
#dans article/views.py  le fonction dashboard est executé avec attribue dashboard

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views                 #import index de views.py

urlpatterns = [
    path('admin/', admin.site.urls),                            #admin pannel
    path('',views.index,name="index"),                          #index.html , vers fonction index dans views.py
    path('about/',views.about,name="about"),                    #about.html , vers fonction about dans views.py
    path('detail/<int:id>', views.detail, name="detail"),       #variable id va etre integer,fonction detail dans views
    path('article/',include("article.urls")),   #si article/ path import le article/urls.py   (articles/)
    path('user/', include("user.urls")),        #si user/ path import le user/urls.py      (articles)

]


#a partir de navbar :  href="/article/dashboard/  , path /article/ envois vers article/url.py selon blog/urls.py
#dans url.py   path  dashboard/  views.dashboard  envois vers fichier  article/views.py fonction dashboard()
#avec attribue  dashboard
#dans article/views.py  le fonction dashboard est executé avec attribue dashboard

templates/includes/navbar.html
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
   <a class="navbar-brand" href="/">YB Blog</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
   </button>


   <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About</a>
           </li>
           <li class="nav-item active">
            <a class="nav-link" href="{% url 'article:articles' %}">Articles</a>
           </li>
        </ul>
        <ul class="navbar-nav ml-auto">
         {% if request.user.is_authenticated %}
            <li class="nav-item active">
            <a class="nav-link" href="/user/logout/">Logout</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="/article/dashboard/">Control Pannel</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="/article/addarticle/">Add Articles</a>
            </li>
          {% else %}
            <li class="nav-item active">
            <a class="nav-link" href="/user/login/">Login</a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="/user/register/">Register</a>
            </li>
          {% endif %}
        </ul>
    </div>
</nav>
</body>
</html>

templates/includes/posttemplate.html
<div class="row align-items-center justify-content-between h-100">
<div class="col">
<i class="fab fa-github text-github small"></i>
<a class="small" href="https://github.com/BlackrockDigital/startbootstrap-blog-post">View on GitHub</a>
</div>
<div class="col d-none d-lg-block">
<ul class="nav responsive-toggler justify-content-center" role="tablist">
<li class="nav-item">
<a class="nav-link active" id="desktopToggle" data-toggle="tab" href="#" role="tab" aria-selected="true">
<i class="fal fa-desktop"></i>
</a>
</li>
</ul>
</div>
</div>